### ISSUE TITLE
[Android 11] Crash on app start

### ISSUE THREAD

**Issue by aca-info** [warren-bank/Android-AirPlay-Client#1]
Hello, 

Thank you for forking this project.
I wanted to test the audio stream to an airport express but the application is crashing as soon as I launch it. 
I'm using the v0.5.0 on a Pocophone F1 on Android 11.
The exception says that it needs android.permission.FOREGROUND_SERVICE.

Can you help me ?

**Comment by warren-bank** [comment]
That was a dumb oversight on my part..
thanks for letting me know;
I'll add the permission today..
along with a minor release.

Funny that when I tested the app in Android 8..
it didn't crash with this exception.

However, regarding audio..
* the upstream app doesn't support playback of audio
* this fork treats audio files the same as video files.. by streaming the URL of the locally hosted audio file to the "/play" AirPlay endpoint
  - AirPlay v1 does __not__ support playing [audio streams](http://nto.github.io/AirPlay.html#audio) in this way
    * AirTunes v1 uses RTSP streams, which is not something I have any intention to implement
  - it will (most likely) __only__ work on [ExoAirPlayer](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver) receiver
    * which is the only receiver that I can test.. and (to be perfectly honest) have any interest in supporting

**Comment by warren-bank** [comment]
PS: there are [other apps](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/issues/4#issuecomment-862789418) out there that specifically implement AirTunes v1..
* I haven't tested any of them..
* but that's where you're most likely to find a successful outcome using real (but outdated) Apple hardware

**Comment by warren-bank** [comment]
[v0.5.1](https://github.com/warren-bank/Android-AirPlay-Client/releases/tag/v0.5.1) release adds some missing permissions..
so you should now be able to test the client app and see what (if anything) happens on your _airport express_ receiver.

**Comment by aca-info** [comment]
Wow !
Thank you very much for the release and your fast answer. :)

I'm not a fan of Apple but I was using the airport as a cheap DAC to stream some audio into a very old HK amplifier.
On linux, I was using [this](https://github.com/hfujita/pulseaudio-raop2) so I think you're right about the RTSP audio.
The only app that works so far on Android is this [one](https://apkpure.com/airmusic-stream-your-music-trial-root/app.airmusic.trial).
But unfortunately it's not open source and only a trial...
I didn't know about Toaster Cast maybe it will work for me also.

There's no crash on the new release anymore but I'm stuck with "No services found".
Maybe it can't detect airport receiver ?

**Comment by aca-info** [comment]
I've also found [this repo](https://github.com/lhzheng880828/AndroidApp) which seems to have an Airtunes player implementation.
I will try to look it this weekend.

**Comment by warren-bank** [comment]
I completely forgot about [_AirMusic_](https://play.google.com/store/apps/details?id=app.airmusic.pro)..
* when I looked at your link, it looked really really familiar
* then I remembered that I'd already played around with it and had it installed on my phone
* not that I have any use for it.. but you're right.. it looks like it does a great job (for its purpose)

I took only a super fast browse through [this repo](https://github.com/lhzheng880828/AndroidApp/tree/master/AirPlay) so far..
* the package name "com.grandstream.cast" doesn't have any Google search results
* based on the other apps jammed into this same repo, I'm guessing this isn't the original author.. but I can't find any copies of this app elsewhere
  - how in the world did you find this? :)
* it looks like it's running Bonjour services for discovery, and netty HTTP servers as a receiver..
  - I'm thinking the easiest way to see what it actually does.. is to just build the thing and run it
  - any interest in a copy of the APK when I do?

**Comment by warren-bank** [comment]
wait wait wait..
your 2nd repo.. [this one](https://github.com/jeremyTyriaux/peeler/blob/master/src/com/example/peeler/AirPlayer.java) is most definitely client code.. and it looks _good_!

**Comment by warren-bank** [comment]
[spec](http://nto.github.io/AirPlay.html#servicediscovery-airtunesservice) says.. supported audio codecs are:
* PCM
* Apple Lossless (ALAC)
* AAC
* AAC ELD (Enhanced Low Delay)

[discussion](https://stackoverflow.com/questions/21131595/convert-from-pcm-to-wav-is-it-possible) on SO says.. WAV is a container format that 99.9% of the time contains PCM data (following a mandatory header).

**Comment by warren-bank** [comment]
[here](https://dpsm.wordpress.com/category/android/) is a great tutorial for how to transcode audio files in any format that is natively supported by Android.. to PCM

rather than writing the PCM buffers to an AudioTrack.. it would be written to the RTSP stream

**Comment by warren-bank** [comment]
Before making any improvements to the "Peeler" app..
I'm curious if its basic functionality works.

I forked it and [built an APK](https://github.com/warren-bank/Android-AirTunes-Client/releases)..
would you be willing to test it?
..remember, this version only supports WAV files.

**Comment by aca-info** [comment]
> how in the world did you find this? :)

By searching in the depths of github ^^ 
(Really just using "airplay/airport express android" search terms and focusing on code instead of repositories)

> any interest in a copy of the APK when I do?

Of course, I can to test it.


Concerning Peeler, that's some great news ! :)
I installed the apk but no luck so far, the "Devices" tab is not showing any receiver and there's nothing in the logs...

**Comment by warren-bank** [comment]
Hmm.. that's not encouraging.

If this client could discover your receiver and play PCM from an audio file, then I'd be willing to tinker with it.
But since it apparently needs much more work.. I apologize, but I'm out.

**Comment by aca-info** [comment]
No problem I understand. I'll try it myself.
Thank you for all the information. :)
