### ISSUE TITLE
Android 14?

### ISSUE THREAD

**Issue by PeterKW** [warren-bank/Android-AirPlay-Client#10]
Sorry if I've not included enough information but a bit confused if I've set it up correctly.

![Screenshot_20240901-205537.png](https://github.com/user-attachments/assets/0daa5b0f-1859-4122-a5e0-bd663177ccbe)

I think I've given it all permissions including access to all files? Might I have done something incorrectly or is this what it is meant to look like? 

Thank you very much

**Comment by warren-bank** [comment]
I actually installed this app again recently for the first time in a very long time.. and had the same bit of momentary confusion: "What do I do now?"

The answer is.. left-hand drawer. If you swipe left-to-right.. you'll access the menu.
